# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:           Sogin lab
tagline:          'E.M. Sogin'
description:      '<a href="https://www.ucmerced.edu" target="_blank">@UC Merced</a>
<br> Symbiosis, microbiology & the environment'
url:              https://esoginlab.github.io
baseurl:          ''
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Maggie Sogin'
  url:            https://twitter.com/MaggieSogin

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

# Build settings
theme: jekyll-theme-hydeout
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

twitter_username: MaggieSogin
github_username:  esogin

# need to add when installing for github pages
remote_theme: fongandrew/hydeout